# Generated by Django 4.0.6 on 2022-08-28 12:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image_path', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'banner图',
                'verbose_name_plural': 'banner图',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': '栏目表',
                'verbose_name_plural': '栏目表',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=20)),
                ('logo_path', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': '公司信息表',
                'verbose_name_plural': '公司信息表',
                'db_table': 'company_contact',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=25)),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='栏目文章详情')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycompany.category')),
            ],
            options={
                'verbose_name': '子栏目表',
                'verbose_name_plural': '子栏目表',
                'db_table': 'sub_category',
            },
        ),
    ]
