# Generated by Django 4.0.6 on 2022-08-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0002_rename_category_id_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_photo',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='logo_picture',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
