# Generated by Django 4.0.6 on 2022-08-28 13:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0003_banner_banner_photo_companycontact_logo_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='栏目文章详情'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=25, verbose_name='子栏目标题'),
        ),
    ]
