# Generated by Django 4.0.6 on 2022-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0004_remove_banner_image_path_alter_subcategory_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontact',
            name='logo_path',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_m_photo',
            field=models.ImageField(default='', upload_to='images', verbose_name='手机端banner图'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_photo',
            field=models.ImageField(default='', upload_to='images', verbose_name='电脑端banner图'),
        ),
    ]
