# Generated by Django 4.0.6 on 2022-08-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0005_remove_companycontact_logo_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_show_photo',
            field=models.ImageField(default='', upload_to='images', verbose_name='广告展示图'),
        ),
    ]
