# Generated by Django 4.0.6 on 2022-08-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0006_banner_banner_show_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_m_photo',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner_photo',
        ),
        migrations.AddField(
            model_name='category',
            name='show_image_m_in',
            field=models.ImageField(default='', upload_to='images', verbose_name='内手机端缩略图'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_image_m_index',
            field=models.ImageField(default='', upload_to='images', verbose_name='外手机端缩略图'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_image_pc_in',
            field=models.ImageField(default='', upload_to='images', verbose_name='内电脑端缩略图'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_image_pc_index',
            field=models.ImageField(default='', upload_to='images', verbose_name='外电脑端缩略图'),
        ),
    ]
