# Generated by Django 4.0.6 on 2022-08-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0007_remove_banner_banner_m_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=25, verbose_name='栏目标题'),
        ),
    ]
