# Generated by Django 4.0.6 on 2022-08-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0010_alter_category_show_image_m_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=0, verbose_name='排序-值越大越靠前'),
        ),
    ]
