# Generated by Django 4.0.6 on 2022-08-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0011_category_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=1, verbose_name='排序-值越大越靠前'),
        ),
    ]
