# Generated by Django 4.0.6 on 2022-08-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0014_rename_index_category_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序-值越大越靠前'),
        ),
    ]
