# Generated by Django 4.0.6 on 2022-08-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0008_alter_category_title'),
        ('mycompany', '0015_alter_category_sort'),
    ]

    operations = [
    ]
